CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    authors VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    published_on DATE NOT NULL,
    publisher VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    city VARCHAR(60) NOT NULL,
    country_region VARCHAR(55) NOT NULL,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    postal_code VARCHAR(18) NOT NULL,
    street_and_house_number VARCHAR(100) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE NOT NULL,
    book_id BIGINT,
    customer_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (book_id) REFERENCES books(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(255) PRIMARY KEY NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities (
    username VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL,
    FOREIGN KEY (username) REFERENCES users(username)
);

